name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        # python-version: ["cp37", "cp39", "cp38", "cp310", "cp311", "cp312"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - shell: bash
        run: |
          python -m pip install --upgrade pip setuptools
          pip install numpy absl-py

          bazelisk test -c opt :all
          bazelisk test -c opt python:all
          bazelisk build -c opt :all
          bazelisk build -c opt python:all

          mkdir action-product
          cp bazel-bin/*_pb2.py action-product/
          cp bazel-bin/python/visqol_lib_py.so action-product/
          cp model/lattice_tcditugenmeetpackhref_ls2_nl60_lr12_bs2048_learn.005_ep2400_train1_7_raw.tflite action-product/
          cp model/libsvm_nu_svr_model.txt  action-product/
      - uses: actions/upload-artifact@v3
        with:
          name: visqol-${{ matrix.os }}-cp312
          path: action-product
